// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

// Injectors from wire.go:

func injectFooBar() *FooBar {
	wireFooA := provideFoo()
	wireFooB := provideFoo()
	fooBar := &FooBar{
		FooA: wireFooA,
		FooB: wireFooB,
	}
	return fooBar
}

func injectEmptyStruct() *Empty {
	wireEmpty := Empty{}
	return wireEmpty
}
