// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

// Injectors from wire.go:

func injectFooBar() *FooBar {
	fooA := provideFoo()
	fooB := provideFoo()
	fooBar := &FooBar{
		FooA: fooA,
		FooB: fooB,
	}
	return fooBar
}

func injectEmptyStruct() *Empty {
	empty := Empty{}
	return empty
}
