// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

// Injectors from wire.go:

func injectFoo(fooA_wired Foo) Foo {
	fooB := provideFoo()
	fooResult := provideAddedFoo(fooA_wired, fooB)
	return fooResult
}
