// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"example.com/bar"
)

// Injectors from wire.go:

func injectedMessage() string {
	wireExported := _wireStringValue
	return wireExported
}

var (
	_wireStringValue = bar.PublicMsg
)
