// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

// Injectors from wire.go:

func injectFoo() Foo {
	named := _wireFooValue
	return named
}

var (
	_wireFooValue = Foo{X: 42}
)
