// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

// Injectors from wire.go:

func injectFooBar() Foo {
	wireFooA := provideFoo()
	wireFooB := provideFoo()
	foo := provideFooBar(wireFooA, wireFooB)
	return foo
}
