// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"example.com/bar"
	"example.com/foo"
	"fmt"
)

// Injectors from wire.go:

func newToStruct(fromStruct *foo.FromStruct) *bar.ToStruct {
	wireValue2 := fromStruct.ValueB
	wireValue1 := fromStruct.ValueA
	toStruct := &bar.ToStruct{
		ValueA: wireValue2,
		ValueB: wireValue1,
	}
	return toStruct
}

// wire.go:

func main() {
	fromStruct := &foo.FromStruct{
		ValueA: "1",
		ValueB: "2",
	}
	toStruct := newToStruct(fromStruct)
	fmt.Println(toStruct.ValueA, toStruct.ValueB)
}
