// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

// Injectors from wire.go:

func injectFoo(wireFooA Foo) Foo {
	wireFooB := provideFoo()
	foo := provideAddedFoo(wireFooA, wireFooB)
	return foo
}
