// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

// Injectors from wire.go:

func inject(wireA_wired string, wireB_wired string) *Foo {
	foo := provideFoo(wireB_wired, wireA_wired)
	return foo
}

func provideFoo(wireB_wired string, wireA_wired string) *Foo {
	foo := &Foo{
		A: wireA_wired,
		B: wireB_wired,
	}
	return foo
}
