// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

// Injectors from wire.go:

func inject(wireA string, wireB string) *Foo {
	foo := provideFoo(wireB, wireA)
	return foo
}

func provideFoo(wireB string, wireA string) *Foo {
	foo := &Foo{
		A: wireA,
		B: wireB,
	}
	return foo
}
