// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

// Injectors from wire.go:

func injectFooBar() Foo {
	wireFooA := provideFooA()
	wireFooB := provideFooB(wireFooA)
	return wireFooB
}
