// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

// Injectors from wire.go:

func injectedMessage() string {
	wireNamed := _wireStringValue
	return wireNamed
}

var (
	_wireStringValue = "Hello, World!"
)
