// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

// Injectors from wire.go:

func injectBar() (*Foo, func()) {
	wireFooA, cleanup := provideFooA()
	wireFooB, cleanup2 := provideFooB(wireFooA)
	return wireFooB, func() {
		cleanup2()
		cleanup()
	}
}
