// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

// Injectors from wire.go:

func injectBar() (*Foo, func()) {
	fooA, cleanup := provideFooA()
	fooB, cleanup2 := provideFooB(fooA)
	return fooB, func() {
		cleanup2()
		cleanup()
	}
}
