// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

// Injectors from wire.go:

func injectFooBar() FooBar {
	wireFooValue := _wireFooValue
	fooBar := provideFooBar(wireFooValue)
	return fooBar
}

var (
	_wireFooValue = Foo(41)
)
